### ISSUE TITLE
Revise urllib3’s version constraint to remove the potential dependency conflicts

### ISSUE THREAD

**Issue by NeolithEra** [zhaoweiho/SecurityManageFramwork#4]
Hi, _**SecurityManageFramwork**_ directly and transitively introduced multiple versions of _**urllib3**_.

As shown in the following full dependency graph of  **_SecurityManageFramwork_**, it directly requires _**urllib3**_ (the latest version)， while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint (_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
SecurityManageFramwork(version range:)
| +-anyjson(version range:==0.3.3)
| +-celery(version range:==4.1.1)
| +-chardet(version range:==3.0.4)
| +-django(version range:>=2.0.11)
| +-pymysql(version range:==0.8.0)
| +-python-nmap(version range:==0.6.1)
| | +-coverage(version range:==4.0.3)
| | +-flake8(version range:==2.5.1)
| | +-mccabe(version range:==0.3.1)
| | +-nose(version range:==1.3.7)
| | +-pep8(version range:==1.7.0)
| | +-pluggy(version range:==0.3.1)
| | +-pudb(version range:==2015.4.1)
| | +-py(version range:==1.4.31)
| | +-pyflakes(version range:==1.0.0)
| | +-pygments(version range:==2.1)
| | +-tox(version range:==2.3.1)
| | +-urwid(version range:==1.3.1)
| | +-virtualenv(version range:==14.0.1)
| +-pytz(version range:==2018.4)
| +-requests(version range:>=2.20.0)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:>=1.23)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
    I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency urllib3, and use urllib3 transitively introduced by request.

@zhaoweiho   Please let me know your choice. I can submit a PR to solve this issue.
Build a good dependency ecosystem for python projects is our common goal ^_^.

**Comment by we1h0** [comment]
Thx @NeolithEra please you can submit a PR to solve this issue^_^.
